import { DataSource } from 'typeorm'

import { Category } from '@/entities/category.entity'
import { Product } from '@/entities/product.entity'
import { env } from '@/env'

import { ProductAutoGeneratedUUID1741044269733 } from './migrations/1741044269733-ProductAutoGeneratedUUID'

export const appDataSource = new DataSource({
  type: 'postgres',
  host: env.DATABASE_HOST,
  port: env.DATABASE_PORT,
  username: env.DATABASE_USER,
  password: env.DATABASE_PASSWORD,
  database: env.DATABASE_NAME,
  entities: [Product, Category],
  migrations: [ProductAutoGeneratedUUID1741044269733],
  logging: env.NODE_ENV === 'development',
})

appDataSource
  .initialize()
  .then(() => {
    console.log('Database typeorm connection established successfully')
  })
  .catch((error) => {
    console.error('Error connecting to database typeorm', error)
  })
